### ISSUE TITLE
Deno has deno.land/x/ already

### ISSUE THREAD

**Issue by zaynv** [denopkg/denopkg.com#1]
Just wanted to mention in case you weren't aware already it was mentioned [here](https://github.com/denoland/deno/issues/1397#issuecomment-449542601) that https://deno.land/x/ exists as an official url redirection for deno packages. Figured it was worth saying here as it seems this is trying to do something similar

**Comment by egoist** [comment]
Thanks, but seems deno.land/x is only for a limit set of repos: https://github.com/denoland/registry/blob/master/x/src/database.json

**Comment by zaynv** [comment]
Yes, that's right. There is a note on the https://deno.land/x/ webpage that says 

> To add a package send a pull request to https://github.com/denoland/registry/blob/master/x/database.json

But I actually am not sure if that means that it is something that they plan to use for the public or if it is just something for their internal stuff so I'll close this out

**Comment by egoist** [comment]
> @kevinkassimo: About registry, there is the deno.land/x/ for redirection of scripts hosted elsewhere, but they are specifically for modules written solely for deno and is similar to golang.org/x/

So I think it is for their internal use.

**Comment by kevinkassimo** [comment]
Hey. `deno.land/x` is intended for public use. The intention of my comment was to clarify that `deno.land/x` is not likely to host ported node packages (as asked in that issue).

Though, Ryan never said that there should only be a single “official” registry

**Comment by egoist** [comment]
Get it, looking forward to a better solution of using third-party libs from deno.land/x without sending pull requests 👌🏻

**Comment by kevinkassimo** [comment]
@egoist True in a way. Ryan's idea is that we should keep Deno core small, so we are moving code that does not rely on bindings to `deno_std`, which is hosted at `deno.land/x/std`

I'll double check with Ryan about this tho.

**Comment by ry** [comment]
Deno is supposed to be a distributed module system, so I welcome more module servers : )
(Ideally github would just have sane URLs to raw content...)
