### ISSUE TITLE
The url https://denopkg.com/ is currently down

### ISSUE THREAD

**Issue by prathithacb** [denopkg/denopkg.com#30]
When we try using [this url,](https://denopkg.com/) we observe that currently it is not working. Please see the attached screenshot. Thanks.

![image](https://user-images.githubusercontent.com/9957554/149941210-a5fbdab8-c5bf-475b-ad3c-280d65b39a82.png)

**Comment by shah** [comment]
We noticed the same in the USA - all our `denopkg.com` module references are showing this DNS error:

![image](https://user-images.githubusercontent.com/47497/149942022-eedec33f-2ee5-49f5-b3b3-3c7b57ebfdbe.png)

**Comment by egoist** [comment]
fixed, sorry for the inconvenice
